#######################################
#
# NBI-Online的各种外部配置项
#
#######################################

#######################################
#
# MongoDB
#
#######################################
db_user: root
db_password: buptweb007
db_address: 49.232.229.126
db_port: 27017
db_authsource: admin

#######################################
#
# Image GC
#
#######################################

# hours
gc_interval: 24

#True or False
gc_mode: False
